export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAIL = "LIKE_POST_FAIL";

export const UN_LIKE_POST_REQUEST = "UN_LIKE_POST_REQUEST";
export const UN_LIKE_POST_SUCCESS = "UN_LIKE_POST_SUCCESS";
export const UN_LIKE_POST_FAIL = "UN_LIKE_POST_FAIL";

export const COMMENT_POST_REQUEST = "COMMENT_POST_REQUEST";
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS";
export const COMMENT_POST_FAIL = "COMMENT_POST_FAIL";
