export const GET_ALL_PROFILE_REQUEST = "GET_ALL_PROFILE_REQUEST";
export const GET_ALL_PROFILE_SUCCESS = "GET_ALL_PROFILE_SUCCESS";
export const GET_ALL_PROFILE_FAIL = "GET_ALL_PROFILE_FAIL";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const FOLLOW_PROFILE_REQUEST = "FOLLOW_PROFILE_REQUEST";
export const FOLLOW_PROFILE_SUCCESS = "FOLLOW_PROFILE_SUCCESS";
export const FOLLOW_PROFILE_FAIL = "FOLLOW_PROFILE_FAIL";

export const UN_FOLLOW_PROFILE_REQUEST = "UN_FOLLOW_PROFILE_REQUEST";
export const UN_FOLLOW_PROFILE_SUCCESS = "UN_FOLLOW_PROFILE_SUCCESS";
export const UN_FOLLOW_PROFILE_FAIL = "UN_FOLLOW_PROFILE_FAIL";

export const EDIT_PROFILE_DETAILS_REQUEST = "EDIT_PROFILE_DETAILS_REQUEST";
export const EDIT_PROFILE_DETAILS_SUCCESS = "EDIT_PROFILE_DETAILS_SUCCESS";
export const EDIT_PROFILE_DETAILS_FAIL = "EDIT_PROFILE_DETAILS_FAIL";
